name: tika_client
description: Dart bindings for Tika server REST API.
version: 1.0.0
homepage: https://github.com/isoos/tika_client
author: Istvan Soos <istvan.soos@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http_client: ^0.5.0
